### ISSUE TITLE
Restaurant profile cant load the google maps correctly

### ISSUE THREAD

**Issue by simay1224** [xiaodan-tang/sprint2021-team-1-repo#27]
When I click any restaurant profile, the map portion says "This page can't load Google Maps correctly."

As a user, I want to see the Google maps correctly so that I can view the location of the restaurant easily.

**Comment by parthmerchant** [comment]
This issue can only be resolved by purchasing a Google Maps API key. At the moment, our project is not receiving any funding :(.
