### ISSUE TITLE
Research and find a database with MOPD compliance data so that the data is readily available to users.

### ISSUE THREAD

**Issue by Niangmodou** [xiaodan-tang/sprint2021-team-1-repo#5]
**User Story**
As a software engineer, I need to research and find a database with MOPD compliance data so that the data is readily available to users.

**Acceptance Criteria**
- The new MOPD data has accurate information about accessibility for restaurants in New York City.
- The data can be stored in the database to be readily available on the front-end interface of DineLine.

**Definition of Done**
- Research all available open-source APIs for accessibility data for restaurants in NYC.
- Accurate MOPD data is available for storage in database.
- Acceptance criteria met.

**Comment by parthmerchant** [comment]
**User Story**

- As a user, I should be able to view the accurate MOPD data from a reputable data source.
- As a restaurant owner, I should be able to view the accurate MOPD data for my restaurant page from a reputable data source.

**Acceptance Criteria**

- The new MOPD data has accurate information about accessibility for restaurants in New York City.
- The data can be stored in the database to be readily available on the front-end interface of DineLine.

**Definition of Done**

- Research all available open-source APIs for accessibility data for restaurants in NYC. 
- Accurate MOPD data is available for storage in database.
- Acceptance criteria met.

**Comment by HahnNYU** [comment]
3/5: data.cityofnewyork.us does not have any MOPD compliance data. I emailed NYC Open data requesting that they create an open data set with the MOPD compliance data we need. Waiting for their response

**Comment by HahnNYU** [comment]
Going to import 2019 data manually like in nyc-accessible-restaurant-advisor repo until NYC Open data adds the MOPD compliance data set we need to use Socrata API
