### ISSUE TITLE
 Alter frond end to show accessibility compliance information for each restaurant 

### ISSUE THREAD

**Issue by Niangmodou** [xiaodan-tang/sprint2021-team-1-repo#6]
**User Story**
As a user I want to be able to easily identify which restaurants are handicap compliant so that I can make better dining decisions that fit my needs.

**Acceptance Criteria**
- Given I am a user, I can easily identify if a restaurant in handicap accessible or not

**Definition of Done**
- MOPD compliance data for each restaurant is communicated to the user.
- Unit tests are written for new code.
- Changes are pushed to repo with build passing.

**Comment by parthmerchant** [comment]
Working on unit testing and getting the build to pass. Frontend changes have been made.

**Comment by parthmerchant** [comment]
1. Modified HTML and JavaScript in the following files (index.html, browse.html, restaurant_detail.html, inspection_records.html) to conditionally add the Compliant badge for MOPD Compliant Restaurants. 
2. Added MOPD_Compliance in utils.py functions for get_latest_inspection_record() and query_inspection_record() to get MOPD data for each individual restaurant.
