### ISSUE TITLE
The web app to automatically pulls MOPD accessibiliy compliance data on a schedule so that the database is automatically updated.

### ISSUE THREAD

**Issue by HahnNYU** [xiaodan-tang/sprint2021-team-1-repo#7]
User story
As a Software engineer, I want the web app to automatically pull MOPD accessibility compliance data on a schedule so that the database is automatically updated.

Acceptance criteria
When the user logs in and sees the most up-to-date and accurate the MOPD accessibility compliance data  
Database gets updated without any further intervention of the software engineers 

Definition of Done
When the web app automatically pulls the data on a schedule and updates the database successfully
Unit tests are written for new code
Changes are pushed to the repo with build passing

**Comment by parthmerchant** [comment]
Request for additional data from NYC Open Data regarding MOPD accessibility is still pending. There is currently no progress regarding automated updates to the Accessibility data.
